{"uuid": "f7d65f42-554e-4181-a249-a0536d022c88", "children": ["b7343c92-fbca-4f46-84d7-a734139c6059", "e07b80d2-1277-4804-b232-7077f0859449", "e356c5b2-1af8-4f28-885e-90518f37a808", "34f47cfa-f900-43e8-a253-cc284f087a14", "002e574d-d9b1-4b18-a0ac-e1cf437c8a1d", "3db0330c-4d18-447e-8bd3-aea22645377d"], "befores": [{"name": "method", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on '192.168.186.128' (timed out)\")\n", "trace": "  File \"D:\\python3\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1117, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\python3\\lib\\site-packages\\_pytest\\fixtures.py\", line 915, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\pytest_automation\\conftest.py\", line 8, in method\n    link_mysql(\"DELETE FROM users WHERE user_name='wjz';\", \"database.ini\", \"dev\")\n  File \"D:\\PycharmProjects\\pytest_automation\\common\\db_link.py\", line 21, in link_mysql\n    db=pymysql.connect(host=confdata[0],port=int(confdata[1]),user=confdata[2],password=confdata[3],db=confdata[4])\n  File \"D:\\python3\\lib\\site-packages\\pymysql\\__init__.py\", line 94, in Connect\n    return Connection(*args, **kwargs)\n  File \"D:\\python3\\lib\\site-packages\\pymysql\\connections.py\", line 325, in __init__\n    self.connect()\n  File \"D:\\python3\\lib\\site-packages\\pymysql\\connections.py\", line 630, in connect\n    raise exc\n"}, "start": 1621995516617, "stop": 1621995526645}], "start": 1621995516617, "stop": 1621995527064}